spring:
  application:
    name: "Instagram"
  jpa:
      hibernate:
        ddl-auto: validate

  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true
    expose-spring-macro-helpers: true

  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: Ahmatbek
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yml

logging:
  level:
    root: info
    org:
      springframework:
        security: debug
    web: info
    sql: error
  file:
    path: logs
